test_add (sel.TestCase.TestClass) ... FAIL
test_mul (sel.TestCase.TestClass) ... ok
test_min (sel.TestCase.TestClass) ... ok

======================================================================
FAIL: test_add (sel.TestCase.TestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\PythonProject\Learn\UIauto\sel\TestCase.py", line 10, in test_add
    self.assertNotEqual(3,add(1,2))
AssertionError: 3 == 3

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (failures=1)
